[package]
name = "hudsucker"
version = "0.12.0"
edition = "2021"
description = "MITM HTTP/S proxy"
documentation = "https://docs.rs/hudsucker"
readme = "README.md"
homepage = "https://github.com/omjadas/hudsucker"
repository = "https://github.com/omjadas/hudsucker"
license = "MIT OR Apache-2.0"
keywords = ["http", "proxy"]
categories = ["network-programming"]
exclude = [".github/"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
async-compression = { version = "0.3", features = ["tokio", "brotli", "gzip", "zlib", "zstd"] }
async-trait = "0.1"
bytes = "1"
futures = "0.3"
http = "0.2"
hyper = { version = "0.14", features = ["client", "http1", "server", "stream", "tcp"] }
hyper-rustls = { version = "0.23", default-features = false, features = ["http1", "logging", "tls12", "webpki-tokio"], optional = true }
hyper-tls = { version = "0.5", optional = true }
hyper-tungstenite = "0.5"
moka = { version = "0.7", features = ["future"], optional = true }
openssl = { version = "0.10", optional = true }
rcgen = { version = "0.9", features = ["x509-parser"], optional = true }
thiserror = "1"
time = { version = "0.3", optional = true }
tokio = { version = "1", features = ["io-util", "rt"] }
tokio-rustls = "0.23"
tokio-tungstenite = { version = "0.16", features = ["rustls-tls-webpki-roots"] }
tokio-util = { version = "0.7", features = ["io"] }
tracing = { version = "0.1", features = ["log"] }

[dev-dependencies]
rustls-pemfile = "0.3"
tokio = { version = "1", features = ["full"] }
tracing-subscriber = "0.3"

[features]
default = ["rcgen-certs", "rustls-client"]
full = ["http2", "native-tls-client", "openssl-certs", "rcgen-certs", "rustls-client"]
http2 = ["hyper/http2", "hyper-rustls/http2"]
native-tls-client = ["hyper-tls"]
openssl-certs = ["openssl", "moka"]
rcgen-certs = ["rcgen", "moka", "time"]
rustls-client = ["hyper-rustls"]

[[example]]
name = "openssl"
required-features = ["openssl-certs"]
