[package]
name = "hudsucker"
version = "0.8.1"
edition = "2021"
description = "MITM HTTP/S proxy"
documentation = "https://docs.rs/hudsucker"
readme = "README.md"
homepage = "https://github.com/omjadas/hudsucker"
repository = "https://github.com/omjadas/hudsucker"
license = "MIT"
keywords = ["http", "proxy"]
categories = ["network-programming"]
exclude = [".github/"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
async-compression = { version = "0.3", features = ["tokio", "brotli", "gzip", "zlib", "zstd"] }
async-trait = "0.1"
bytes = "1"
chrono = "0.4"
futures = "0.3"
http = "0.2"
hyper = { version = "0.14", features = ["client", "http1", "server", "stream", "tcp"] }
hyper-rustls = { version = "0.23", features = ["webpki-roots"], optional = true }
hyper-tls = { version = "0.5", optional = true }
hyper-tungstenite = "0.5"
log = "0.4"
moka = { version = "0.6", features = ["future"], optional = true }
openssl = { version = "0.10", optional = true }
rcgen = { version = "0.8", features = ["x509-parser"], optional = true }
thiserror = "1"
tokio = { version = "1", features = ["io-util", "rt"] }
tokio-rustls = "0.23"
tokio-tungstenite = { version = "0.16", features = ["rustls-tls-webpki-roots"] }
tokio-util = { version = "0.6", features = ["io"] }

[dev-dependencies]
env_logger = "0.9"
rustls-pemfile = "0.2"
tokio = { version = "1", features = ["full"] }

[features]
default = ["rcgen-certs", "rustls-client"]
full = ["http2", "openssl-certs", "rcgen-certs"]
http2 = ["hyper/http2", "hyper-rustls/http2"]
native-tls-client = ["hyper-tls"]
openssl-certs = ["openssl", "moka"]
rcgen-certs = ["rcgen", "moka"]
rustls-client = ["hyper-rustls"]

[[example]]
name = "openssl"
required-features = ["openssl-certs"]
