[package]
name = "hudsucker"
version = "0.17.0"
edition = "2021"
description = "MITM HTTP/S proxy"
documentation = "https://docs.rs/hudsucker"
readme = "README.md"
homepage = "https://github.com/omjadas/hudsucker"
repository = "https://github.com/omjadas/hudsucker"
license = "MIT OR Apache-2.0"
keywords = ["http", "proxy"]
categories = ["network-programming"]
exclude = [".github/"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
async-compression = { version = "0.3.7", features = ["tokio", "brotli", "gzip", "zlib", "zstd"], optional = true }
async-trait = "0.1.7"
bytes = "1.0.0"
futures = "0.3.11"
http = "0.2.0"
hyper = { version = "0.14.7", features = ["client", "http1", "server", "stream", "tcp"] }
hyper-rustls = { version = "0.23.0", default-features = false, features = ["http1", "logging", "tls12", "webpki-tokio"], optional = true }
hyper-tls = { version = "0.5.0", optional = true }
hyper-tungstenite = "0.6.0"
moka = { version = "0.8.0", features = ["future"], optional = true }
openssl = { version = "0.10.25", optional = true }
rand = { version = "0.8.0", optional = true }
rcgen = { version = "0.9.0", features = ["x509-parser"], optional = true }
thiserror = "1.0.23"
time = { version = "0.3.1", optional = true }
tokio = { version = "1.6.1", features = ["rt"] }
tokio-rustls = "0.23.0"
tokio-tungstenite = { version = "0.17.0", features = ["rustls-tls-webpki-roots"] }
tokio-util = { version = "0.7.0", features = ["io"], optional = true }
tracing = { version = "0.1.21", features = ["log"] }

[dev-dependencies]
criterion = { version = "0.3.5", features = ["async_tokio"] }
hyper-tls = "0.5.0"
reqwest = "0.11.10"
rustls-pemfile = "1.0.0"
tls-listener = { version = "0.5.1", features = ["rustls", "hyper-h1", "hyper-h2"] }
tokio = { version = "1.6.1", features = ["full"] }
tokio-native-tls = "0.3.0"
tracing-subscriber = "0.3.0"
x509-parser = "0.13.1"

[features]
default = ["decoder", "rcgen-certs", "rustls-client"]
full = ["http2", "native-tls-client", "openssl-certs", "rcgen-certs", "rustls-client"]
http2 = ["hyper/http2", "hyper-rustls?/http2"]
decoder = ["dep:async-compression", "dep:tokio-util", "tokio/io-util"]
native-tls-client = ["dep:hyper-tls"]
openssl-certs = ["dep:openssl", "dep:moka"]
rcgen-certs = ["dep:rcgen", "dep:moka", "dep:time", "dep:rand"]
rustls-client = ["dep:hyper-rustls"]

[[example]]
name = "log"
required-features = ["rcgen-certs", "rustls-client"]

[[example]]
name = "noop"
required-features = ["rcgen-certs", "rustls-client"]

[[example]]
name = "openssl"
required-features = ["openssl-certs", "rustls-client"]

[[test]]
name = "openssl_ca"
required-features = ["decoder", "openssl-certs"]

[[test]]
name = "rcgen_ca"
required-features = ["decoder", "rcgen-certs"]

[[bench]]
name = "certificate_authorities"
harness = false
required-features = ["openssl-certs", "rcgen-certs"]

[[bench]]
name = "decoder"
harness = false
required-features = ["decoder"]

[[bench]]
name = "proxy"
harness = false
required-features = ["rcgen-certs", "rustls-client"]
