[package]
name = "rustproxy"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
ct-logs = "^0.8"
http = "0.2.4"
hyper = { version = "0.14.11", features = ["full"] }
hyper-rustls = "0.22.1"
log = "0.4.14"
rcgen = "0.8.12"
rustls = "0.19.1"
thiserror = "1.0.26"
tokio = { version = "1.10.0", features = ["full"] }
tokio-rustls = "0.22.0"
webpki-roots = "0.21.1"
